### ISSUE TITLE
Bootstrap.css isn't present in public folder

### ISSUE THREAD

**Issue by 3rdp** [ziogas/brunch-with-es6-jquery-twitter-bootstrap-autoreload#1]
What do I have to do to access bootstrap? I tried importing it in styles.css, mentioning it in index.html. None of them helped.

**Comment by 3rdp** [comment]
Oh, somehow brunch didn't clone your repo at all. It created a new project. That's really strange, sorry.

**Comment by ziogas** [comment]
Hello,

Yes, command `brunch new DIRECTORY -s ziogas/brunch-with-es6-jquery-twitter-bootstrap-autoreload` creates a new project under DIRECTORY. Then entering that directory and doing `npm install` should cover all the needed dependencies as [brunch-config.js](https://github.com/ziogas/brunch-with-es6-jquery-twitter-bootstrap-autoreload/blob/master/brunch-config.js#L16) knows how to handle bootstrap css.
